### ISSUE TITLE
GUI Compatibility Issue

### ISSUE THREAD

**Issue by kenijey** [kamildanak/EnderPay#1]
Can you add a config for set the X&Y location of the Credits GUI please? Thank you.
![credit](https://cloud.githubusercontent.com/assets/24831406/23155744/9500339e-f81c-11e6-81f8-56fcb9817e04.PNG)
Thirst feature is from the mod **Tough As Nails**

**Comment by kamildanak** [comment]
Added new config options in 6b5002ce49a750edad77f1c48d9e5ebe805d921b
New config options: positionRelative (true - relative - from where it would be displayed without change, false - absolute - from top left edge of the screen), xOffset, yOffset.

**Comment by kenijey** [comment]
Thanks so much. We are waiting for the new release.
