### ISSUE TITLE
Have a visual confirmation in chat that tells the player they have received or send coins.

### ISSUE THREAD

**Issue by MeWulf** [kamildanak/EnderPay#14]
Example:
"You send 300 coins to PLAYERNAME"
"You received 300 coins to PLAYERNAME"

**Comment by kamildanak** [comment]
The following messages were added in 2eee784ab1ecc3016a8a6d3b170f2ad03befd23
+commands.pay.sent=You transferred %s %s to %s [You transferred 300 coins to PLAYERNAME]
+commands.pay.received=You received %s %s from %s [You received 300 coins from PLAYERNAME]
