### ISSUE TITLE
[1.10.2] Make the credits invisible in spectator mode?

### ISSUE THREAD

**Issue by DeadSix27** [kamildanak/EnderPay#5]
As of now in **1.10.2** they show up even in spectator mode:

![image](https://cloud.githubusercontent.com/assets/1492505/23332108/f61e8f7c-fb73-11e6-85fe-7d3377aec85a.png)

**Comment by kamildanak** [comment]
Fixed in 1d28269da391ec4b5acc065b330caac06a63d3ce
