### ISSUE TITLE
Friendly Request: Credit Drop on Death(configurable) (PvP)

### ISSUE THREAD

**Issue by kenijey** [kamildanak/EnderPay#7]
Can you add credit drop feature for PvP? When a player kills a player, he will get configurable amount of money/credit from him. Config option should be in percentage. 
For example: I have 100 credits, and a player has 100 credits. I configured the drop amount to %50, so i killed him, i got 50 credits from him. I have 150, he has 50.
It would be lovely, please help about it. It can be configurable to activate this feature. But i think it would be satisfying for PvP. 
Thanks.

**Comment by kamildanak** [comment]
Added new config option in 1.12-0.0.5.1.
d85ce3b70a1764d9a59dd5afc6b56145eabb58b8 e761f88e963cd17f57447e7c1c2c4dde15f4bc58 908e347c5e86df0593eb7d1efb077da4b3a5db72 561145e3feb246a8daca111b4f2904e91e2a0b46

**Comment by kenijey** [comment]
thank you very much!!!
