### ISSUE TITLE
Admin Banknote For OP Players

### ISSUE THREAD

**Issue by kenijey** [kamildanak/EnderPay#8]
Can you add uncraftable banknote that never expires and has infinite credits? i will put it in vending block to buy something from players. I made 99999... credits banknote but it expires after a time. 
Thanks.

**Comment by kamildanak** [comment]
You can set vending block to be infinite using wrench, infinite vending machine will not check if the banknote expired.

**Comment by kenijey** [comment]
oh, wasn't aware. thanks a lot! and btw, we're waiting for pvp money gain feature :D
