### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by TekuSP** [kamildanak/EnderPay#9]
Users without OP can't use /pay etc.

Should I have some permissions mod? Or this is a bug?

**Comment by kamildanak** [comment]
Fixed in 83ed2e7d40e9d2adf0be45b5b9af007cc6aa4b3b
Thank you for reporting.

**Comment by TekuSP** [comment]
Maybe you should push it too CurseForge too, its pretty big bug... making mod not functional...
